name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Debug npm configuration
      run: |
        echo "NPM cache directory: $(npm config get cache)"
        ls -al /home/runner/.npm
    - name: Clear npm cache
      run: npm cache clean -f
    - run: npm install
    # - name: Run npm start
    - run: npm start
